Controllers/BookmarkController.cs
using Microsoft.AspNetCore.Mvc;
using quizweb.Services.Implementations;
using quizweb.Services.Interfaces;
using quizweb.ViewModels.BookMark;

namespace quizweb.Controllers
{
    public class BookmarkController : Controller
    {
        private readonly IMarkedQuestionService _markedQuestionService;
        private readonly IProgressQuestionSetService _progressQuestionSetService;
        private readonly IQuestionSetService _questionSetService;

        public BookmarkController(IMarkedQuestionService markedQuestionService, IProgressQuestionSetService progressQuestionSetService, IQuestionSetService questionSetService)
        {
            _markedQuestionService = markedQuestionService;
            _progressQuestionSetService = progressQuestionSetService;
            _questionSetService = questionSetService;
        }
        
        public async Task<IActionResult> Index()
        {
            var username = User.Identity?.Name;
            if (string.IsNullOrEmpty(username))
            {
                return Unauthorized();
            }

            var progressList = await _progressQuestionSetService.GetAllProgressQuestionSets(username);
            var markedList = await _markedQuestionService.GetAllMarkedQuestionsAsync(username);
            var createdList = await _questionSetService.GetAllCreatedQuestionSetsAsync(username);

            var bookmarkViewModel = new BookMarkViewModel()
            {
                ProgressQuestionSetList = progressList,
                CreatedQuestionList = createdList,
                MarkedQuestionList = markedList
            };

            return View(bookmarkViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveQuestion([FromBody] int questionId)
        {
            var username = User.Identity?.Name;
            if (string.IsNullOrEmpty(username))
            {
                return Unauthorized();
            }

            await _markedQuestionService.AddMarkedQuestion(username, questionId);

            return NoContent();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnsaveQuestion([FromBody] int questionId)
        {
            var username = User.Identity?.Name;
            if (string.IsNullOrEmpty(username))
            {
                return Unauthorized();
            }

            await _markedQuestionService.RemoveMarkedQuestion(username, questionId);

            return NoContent();
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using quizweb.DTOs;
using quizweb.Services.Interfaces;
using quizweb.ViewModels;
using System.Globalization;
using quizweb.ViewModels.User;

namespace quizweb.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ILogger<ProfileController> _logger;
        private readonly IUserService _userService;

        public ProfileController(ILogger<ProfileController> logger, IUserService userService)
        {
            _logger = logger;
            _userService = userService;
        }


        // GET: ProfileController
        public async Task<IActionResult> Index()
        {
            if (!User.Identity?.IsAuthenticated == true)
            {
                return Unauthorized();
            }
            var username = User.Identity?.Name!;
            var user = await _userService.GetProfileAsync(username);
            if (user == null)
            {
                return NotFound();
            }

            var viewModel = new UserEditViewModel
            {
                Username = user.UserName!,
                Birthday = user.BirthDay.ToString("dd/MM/yyyy"),
                Email = user.Email!,
                Fullname = user.FullName,
                Sex = user.Sex,
            };
            return View(viewModel);
        }



        // POST: ProfileController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateField([FromBody] UpdateFieldRequest request)
        {
            try
            {

                if (!User.Identity?.IsAuthenticated == true)
                {
                    return Json(new { success = false, message = "Unauthorized" });
                }

                var user = await _userService.GetProfileAsync(User.Identity?.Name!);

                if (user == null)
                {
                    return Json(new { success = false, message = "User not found" });
                }

                switch (request.FieldName)
                {
                    case "FullName":
                        user.FullName = request.Value;
                        break;
                    case "Email":
                        user.Email = request.Value;
                        user.NormalizedEmail = request.Value?.Trim().ToUpper();
                        break;
                    case "BirthDay":
                        if (DateOnly.TryParseExact(request.Value, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out var date))
                        {
                            user.BirthDay = date;
                        }
                        else
                        {
                            return Json(new { success = false, message = "Invalid date format" });
                        }
                        break;
                    case "Sex":
                        if (bool.TryParse(request.Value,out var sex))
                        {
                            user.Sex = sex;
                        }else 
                        {
                            return Json(new { success = false, message = "Invalid sex field" });
                        }
                        break;  

                    default:
                        return Json(new { success = false, message = "Invalid field" });
                }


                await _userService.UpdateProfileAsync(user);
                return Json(new { success = true, value = request.Value });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating field");
                return Json(new { success = false, message = "An error occurred while updating the field." });
            }
        }
    }
}

Controllers/RankingController.cs
using Microsoft.AspNetCore.Mvc;
using quizweb.Services.Interfaces;
using quizweb.ViewModels;
using quizweb.ViewModels.Ranking;

namespace quizweb.Controllers
{
    public class RankingController : Controller
    {
        private readonly ILogger<RankingController> _logger;
        private readonly IRankingService _rankingService;

        public RankingController(ILogger<RankingController> logger, IRankingService rankingService)
        {
            _logger = logger;
            _rankingService = rankingService;
        }

        // GET: RankingController
        public async Task<IActionResult> Index()
        {
            var rankings = await _rankingService.GetTopRankingsAsync(10);
            var viewModels = rankings.Select(r => new RankingListViewModel
            {
                Username = r.UserName,
                TotalScore = r.TotalScore
            }).ToList();
            return View(viewModels);
        }

        // GET: RankingController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: RankingController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: RankingController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: RankingController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        // POST: RankingController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: RankingController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: RankingController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - quizweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/quizweb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-family:'Lobster'">quizweb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house" style="color: #000000;"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ranking" asp-action="Index"><i class="fa-solid fa-ranking-star" style="color: #000000;"></i> Ranking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookmark" asp-action="Index"><i class="fa-solid fa-bookmark" style="color: #000000;"></i> Bookmark</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index"><i class="fa-solid fa-user" style="color: #000000;"></i> Profile</a>
                        </li>
                    </ul>
                </div>
                @await Html.PartialAsync("_LoginPartial.cshtml")
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - quizweb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> 